### ISSUE TITLE
TLS

### ISSUE THREAD

**Issue by leoamigud** [travelaudience/kubernetes-nexus#38]
I am trying to setup nexus via HTTPS following instructions.

I've created a static IP address named "nexus" and updated ingress settings as:
*kubernetes.io/ingress.global-static-ip-name: nexus*

after ingress and nexus-proxy deployments i still dont see that IP is use and kube-lego is failing to *access nexus to setup the certificate: authorization failed after 1m0s: reachability test failed: wrong status code '404'" context=acme domain=containers.mydomain.com*

Please suggest,
Leo

**Comment by pires** [comment]
Hello @leoamigud! So did you find the solution?

**Comment by leoamigud** [comment]
Yes, thank you. Basically, it was a combination of issues. One - it MUST be a global static IP (not the regional one).
