### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by edmacabebe** [travelaudience/kubernetes-nexus#52]
https://github.com/travelaudience/core-nexus-kubernetes/tree/create-helm-chart/helm/nexus#after-installing-the-chart

upon completion of helm install nexus, the link above is suggested by the tool, but is broken

**Comment by jeff-knurek** [comment]
Indeed, the link is broken. But this was a bug in the helm chart itself, and is addressed in this PR https://github.com/helm/charts/pull/14086
